/**
 * Shared conversation title generation service.
 *
 * Provides a single reusable primitive for generating and persisting
 * conversation titles across all creation paths. Enforces a safe
 * overwrite policy: only replaceable placeholder/system titles are
 * overwritten, never user-provided custom titles.
 */

import { resolveDefaultProfileKey } from "../config/llm-resolver.js";
import { getConfig } from "../config/loader.js";
import { getConfiguredProvider } from "../providers/provider-send-message.js";
import type { Provider } from "../providers/types.js";
import { runBtwSidechain } from "../runtime/btw-sidechain.js";
import { assertPooledRuntimeAsyncOperationSupported } from "../runtime/pooled-runtime-policy.js";
import { publishConversationTitleChanged } from "../runtime/sync/resource-sync-events.js";
import { getLogger } from "../util/logger.js";
import { Mutex } from "../util/mutex.js";
import {
  getConversation,
  getMessages,
  resolveOverrideProfile,
  updateConversationTitle,
} from "./conversation-crud.js";
import {
  resolvePersistedTitleContext,
  type TitleContext,
  type TitleOrigin,
} from "./conversation-title-context.js";

export type {
  TitleContext,
  TitleOrigin,
} from "./conversation-title-context.js";

const log = getLogger("conversation-title-service");

// ── Placeholder / loading state ──────────────────────────────────────

export const GENERATING_TITLE = "Generating title...";
const UNTITLED_FALLBACK = "Untitled Conversation";

// ── `conversations.isAutoTitle` values ───────────────────────────────
//
// Most readers treat the column as a boolean ("not user-set"); the two
// distinct non-zero values let the title pipeline tell HOW a title was set.

/** Title was generated by an LLM from conversation content. */
export const AUTO_TITLE_LLM = 1;
/**
 * Title was derived deterministically from bootstrap context — no LLM call,
 * no user input. Unlike LLM titles, these stay replaceable: the first
 * genuine user message in the conversation upgrades them to an LLM title
 * (see `canReplaceTitle`).
 */
export const AUTO_TITLE_DETERMINISTIC = 2;

// ── Replaceability check ─────────────────────────────────────────────

const REPLACEABLE_PATTERNS = [
  /^Runtime:\s/,
  /^New Conversation$/,
  /^Untitled$/,
  /^Untitled Conversation$/,
  /^Generating title\.\.\.$/,
];

/**
 * Check whether a title is a system-generated placeholder that can be
 * safely overwritten by auto-generated titles. Returns `false` for
 * user-provided custom titles.
 */
export function isReplaceableTitle(title: string | null): boolean {
  if (title == null || title.trim() === "") return true;
  return REPLACEABLE_PATTERNS.some((pattern) => pattern.test(title));
}

/**
 * Whether auto-generation may overwrite the conversation's current title.
 * True for placeholder/system titles and for deterministic bootstrap titles
 * (`AUTO_TITLE_DETERMINISTIC`); false for user-set custom titles and titles
 * already generated by an LLM.
 */
function canReplaceTitle(conversation: {
  title: string | null;
  isAutoTitle: number;
}): boolean {
  return (
    isReplaceableTitle(conversation.title) ||
    conversation.isAutoTitle === AUTO_TITLE_DETERMINISTIC
  );
}

/**
 * Derive a deterministic title from bootstrap context without an LLM call.
 * Used for background/system conversations (heartbeat runs, scheduled jobs,
 * subagents, retrospectives) where an LLM-generated title is not worth the
 * tokens — the bootstrap `systemHint` already names the work. Persist it
 * with `AUTO_TITLE_DETERMINISTIC` so a later genuine user message can still
 * upgrade it to an LLM title.
 */
export function deriveDeterministicTitle(context: TitleContext): string {
  const base = deriveFallbackTitle(context) ?? UNTITLED_FALLBACK;
  return truncateTitle(base.replace(/\s+/g, " ").trim());
}

// ── Title generation ─────────────────────────────────────────────────

export interface GenerateTitleParams {
  conversationId: string;
  /** Provider to use for LLM call. Falls back to getConfiguredProvider(). */
  provider?: Provider;
  /** Context about how/where the conversation was created. */
  context?: TitleContext;
  /** User message text (first turn). */
  userMessage?: string;
  /** Assistant response text (first turn). */
  assistantResponse?: string;
  /** Abort signal. */
  signal?: AbortSignal;
}

interface TitleProviderAttempt {
  provider: Provider;
  profile?: string;
}

const INTERACTIVE_TITLE_ORIGINS = new Set<TitleOrigin>([
  "runtime_api",
  "channel_inbound",
  "voice_outbound",
  "voice_inbound",
  "local",
]);

function resolveConversationTitleContext(
  conversation: ReturnType<typeof getConversation>,
  context?: TitleContext,
): TitleContext | undefined {
  const persistedContext = resolvePersistedTitleContext(conversation);

  // Persisted system provenance is authoritative for compatibility rows. Keep
  // any richer call-site hints, but do not let an interactive-looking call
  // accidentally route a stored schedule/background conversation as chat.
  if (
    persistedContext &&
    !INTERACTIVE_TITLE_ORIGINS.has(persistedContext.origin)
  ) {
    return context
      ? { ...context, origin: persistedContext.origin }
      : persistedContext;
  }

  return context ?? persistedContext;
}

function resolveConversationTitleProfile(
  conversation: ReturnType<typeof getConversation>,
  context?: TitleContext,
): string | undefined {
  if (conversation && conversation.conversationType !== "standard") {
    return undefined;
  }

  if (context && !INTERACTIVE_TITLE_ORIGINS.has(context.origin)) {
    return undefined;
  }

  const conversationProfile = resolveOverrideProfile(conversation);
  if (conversationProfile) return conversationProfile;

  const { llm } = getConfig();
  return llm.activeProfile ?? resolveDefaultProfileKey("mainAgent", llm);
}

async function resolveConversationTitleProvider(
  conversationId: string,
  conversation: ReturnType<typeof getConversation>,
  provider?: Provider,
  context?: TitleContext,
): Promise<Provider | null> {
  if (provider) return provider;

  const titleProfile = resolveConversationTitleProfile(conversation, context);
  return getConfiguredProvider("conversationTitle", {
    ...(titleProfile
      ? { forceOverrideProfile: true, overrideProfile: titleProfile }
      : {}),
    selectionSeed: conversationId,
  });
}

function isUsableProfile(
  profile: ReturnType<typeof getConfig>["llm"]["profiles"][string] | undefined,
): boolean {
  return (
    profile != null &&
    profile.status !== "disabled" &&
    (typeof profile.model === "string" ||
      typeof profile.provider === "string" ||
      typeof profile.provider_connection === "string" ||
      profile.mix != null)
  );
}

function isUserProfile(
  profile: ReturnType<typeof getConfig>["llm"]["profiles"][string] | undefined,
): boolean {
  return isUsableProfile(profile) && profile?.source !== "managed";
}

/**
 * Resolve more than one user-owned profile for interactive titles. A title is
 * a best-effort side effect, so a stale model, expired credential, or provider
 * outage must not leave the conversation permanently untitled when another
 * configured BYOK profile can serve the request.
 */
async function resolveTitleProviderAttempts(
  conversationId: string,
  conversation: ReturnType<typeof getConversation>,
  explicitProvider: Provider | undefined,
  context?: TitleContext,
): Promise<TitleProviderAttempt[]> {
  if (explicitProvider) return [{ provider: explicitProvider }];

  const isInteractive =
    !context || INTERACTIVE_TITLE_ORIGINS.has(context.origin);

  // Background and scheduled work stays on the configured title route. Only
  // interactive chat is allowed to prefer the user's active/BYOK profiles.
  if (
    !isInteractive ||
    (conversation != null && conversation.conversationType !== "standard")
  ) {
    try {
      const provider = await resolveConversationTitleProvider(
        conversationId,
        conversation,
        undefined,
        context,
      );
      return provider ? [{ provider }] : [];
    } catch (err) {
      log.warn(
        { err, conversationId },
        "Unable to resolve configured conversation title provider",
      );
      return [];
    }
  }

  const config = getConfig();
  const profileKeys: string[] = [];
  const customCostProfile = "custom-cost-optimized";
  const activeProfile = config.llm.activeProfile;
  const conversationProfile = resolveOverrideProfile(conversation);
  const conversationProfileConfig = conversationProfile
    ? config.llm.profiles[conversationProfile]
    : undefined;
  const hasUserFallback =
    isUserProfile(config.llm.profiles[customCostProfile]) ||
    (activeProfile != null &&
      isUserProfile(config.llm.profiles[activeProfile]));

  if (
    conversationProfile &&
    (!hasUserFallback || isUserProfile(conversationProfileConfig))
  ) {
    profileKeys.push(conversationProfile);
  }
  if (isUserProfile(config.llm.profiles[customCostProfile])) {
    profileKeys.push(customCostProfile);
  }
  if (activeProfile && isUserProfile(config.llm.profiles[activeProfile])) {
    profileKeys.push(activeProfile);
  }

  const attempts: TitleProviderAttempt[] = [];
  for (const profile of [...new Set(profileKeys)]) {
    try {
      const provider = await getConfiguredProvider("conversationTitle", {
        overrideProfile: profile,
        forceOverrideProfile: true,
        selectionSeed: conversationId,
      });
      if (provider) attempts.push({ provider, profile });
    } catch (err) {
      log.warn(
        { err, conversationId, profile },
        "Unable to resolve conversation title BYOK profile",
      );
    }
  }

  // Do not silently switch an interactive user to a managed title provider
  // after a BYOK profile was configured but could not be resolved.
  if (attempts.length > 0 || profileKeys.length > 0) return attempts;

  try {
    const provider = await getConfiguredProvider("conversationTitle", {
      selectionSeed: conversationId,
    });
    return provider ? [{ provider }] : [];
  } catch (err) {
    log.warn(
      { err, conversationId },
      "Unable to resolve fallback conversation title provider",
    );
    return [];
  }
}

/**
 * Generate a conversation title via LLM and persist it, but only if the
 * current title is still replaceable (safe overwrite policy).
 */
export async function generateAndPersistConversationTitle(
  params: GenerateTitleParams,
): Promise<{ title: string; updated: boolean }> {
  const { conversationId, context, userMessage, assistantResponse, signal } =
    params;

  // Check current title is replaceable
  const conversation = getConversation(conversationId);
  if (conversation && !canReplaceTitle(conversation)) {
    return { title: conversation.title!, updated: false };
  }

  const effectiveContext = resolveConversationTitleContext(
    conversation,
    context,
  );

  const providerAttempts = await resolveTitleProviderAttempts(
    conversationId,
    conversation,
    params.provider,
    effectiveContext,
  );
  if (providerAttempts.length === 0) {
    return persistFallbackTitle(conversationId, effectiveContext, userMessage);
  }

  const prompt = buildTitlePrompt(
    effectiveContext,
    userMessage,
    assistantResponse,
  );
  let title = "";
  let lastError: unknown;
  for (const attempt of providerAttempts) {
    try {
      const result = await runBtwSidechain({
        content: prompt,
        provider: attempt.provider,
        systemPrompt: buildTitleSystemPrompt(),
        tools: [],
        callSite: "conversationTitle",
        signal,
        timeoutMs: 15_000,
      });
      title = normalizeTitle(result.text);
      if (title) break;
    } catch (err) {
      lastError = err;
      log.warn(
        { err, conversationId, profile: attempt.profile },
        "Conversation title provider attempt failed",
      );
    }
  }
  if (title) {
    // Re-check replaceability before persisting (race guard)
    const current = getConversation(conversationId);
    if (current && !canReplaceTitle(current)) {
      return { title: current.title!, updated: false };
    }

    updateConversationTitle(conversationId, title, AUTO_TITLE_LLM);
    publishConversationTitleChanged(conversationId, title);
    log.info({ conversationId, title }, "Auto-generated conversation title");
    return { title, updated: true };
  }

  // No text in response — use fallback
  // Re-check replaceability before persisting (race guard — same as the
  // text-response path above). A concurrent custom rename may have landed
  // while the LLM request was in-flight; writing unconditionally would
  // clobber the user's intent.
  const currentForFallback = getConversation(conversationId);
  if (currentForFallback && !canReplaceTitle(currentForFallback)) {
    return { title: currentForFallback.title!, updated: false };
  }

  if (lastError) {
    log.warn(
      { err: lastError, conversationId },
      "All conversation title provider attempts failed",
    );
  }
  return persistFallbackTitle(conversationId, effectiveContext, userMessage);
}

// ── Serial title-generation queue ────────────────────────────────────

/**
 * Each title generation makes an LLM call. Without serialization, burst
 * conversation creation (e.g. 5 new chats in quick succession) fires N
 * concurrent requests that can hit provider rate limits or contend for
 * API capacity, causing later calls to time out and fall back to
 * "Untitled Conversation".
 *
 * A serial queue ensures at most one title-generation LLM call is
 * in-flight at a time. Each call is lightweight (~1–3 s for a ≤5-word
 * title), so the added serial latency is modest and invisible to the
 * user (new conversations retain the stable "New Conversation" placeholder
 * during the wait). Both initial generation and second-pass regeneration
 * share this queue since they hit the same provider.
 */
export const titleMutex = new Mutex();

/**
 * Awaitable, serialized title generation for request-bound runtimes.
 *
 * Unlike the queue wrapper below, this promise remains attached to the
 * caller's request. Pooled workers use it before releasing their tenant lease,
 * so provider resolution, persistence, and title broadcasts cannot escape into
 * the next tenant's lease.
 */
export function generateConversationTitleRequestBound(
  params: GenerateTitleParams,
): Promise<{ title: string; updated: boolean }> {
  return titleMutex.withLock(() => generateAndPersistConversationTitle(params));
}

/**
 * Fire-and-forget wrapper for title generation. Failures are logged
 * but do not propagate. Legacy loading placeholders are replaced with
 * a stable fallback title so loading state is never permanent.
 *
 * Calls are serialized via {@link titleMutex} so burst conversation
 * creation does not overwhelm the LLM provider.
 */
export function queueGenerateConversationTitle(
  params: GenerateTitleParams,
): void {
  assertPooledRuntimeAsyncOperationSupported("conversation title jobs");
  void generateConversationTitleRequestBound(params).catch((err) => {
    log.warn(
      { err, conversationId: params.conversationId },
      "Failed to generate conversation title (non-fatal)",
    );
    // Replace a loading or deterministic fallback title with the best
    // request-local title available.
    try {
      const conversation = getConversation(params.conversationId);
      if (conversation && canReplaceTitle(conversation)) {
        persistFallbackTitle(
          params.conversationId,
          params.context,
          params.userMessage,
        );
      }
    } catch {
      // Best-effort
    }
  });
}

// ── Title regeneration (second pass) ─────────────────────────────────

export interface RegenerateTitleParams {
  conversationId: string;
  provider?: Provider;
  /** Explicit origin when the trigger already resolved persisted provenance. */
  context?: TitleContext;
  signal?: AbortSignal;
  /**
   * Request-local transcript to title from. Pooled workers pass this from the
   * successful stop hook so regeneration does not depend on a detached read
   * after the tenant lease is released.
   */
  recentMessages?: ReadonlyArray<TitleTranscriptMessage>;
}

export interface TitleTranscriptMessage {
  role: "user" | "assistant";
  text: string;
}

/**
 * Re-generate a conversation title using the last 3 stored messages.
 * Only fires when the current title was auto-generated (isAutoTitle = 1).
 * Skips if the user has manually renamed the conversation.
 */
export async function regenerateConversationTitle(
  params: RegenerateTitleParams,
): Promise<{ title: string; updated: boolean }> {
  const { conversationId, context, signal } = params;

  const conversation = getConversation(conversationId);
  if (!conversation || !conversation.isAutoTitle) {
    return { title: conversation?.title ?? UNTITLED_FALLBACK, updated: false };
  }

  const effectiveContext = resolveConversationTitleContext(
    conversation,
    context,
  );

  const providerAttempts = await resolveTitleProviderAttempts(
    conversationId,
    conversation,
    params.provider,
    effectiveContext,
  );

  const recentMessages =
    params.recentMessages?.slice(-3) ??
    getMessages(conversationId)
      .slice(-3)
      .map((message) => ({
        role:
          message.role === "user" ? ("user" as const) : ("assistant" as const),
        text: extractTextForTitle(message.content),
      }));
  if (recentMessages.length === 0) {
    return { title: conversation.title ?? UNTITLED_FALLBACK, updated: false };
  }

  const prompt = buildRegenerationPrompt(recentMessages);
  // Skip the LLM call if no messages yielded extractable text — the prompt
  // would be just the "Recent messages:" header, and the model tends to
  // fabricate a meta-title about the emptiness rather than decline.
  if (!/\n(?:User|Assistant): /.test(prompt)) {
    return { title: conversation.title ?? UNTITLED_FALLBACK, updated: false };
  }
  let title = "";
  let lastError: unknown;
  for (const attempt of providerAttempts) {
    try {
      const result = await runBtwSidechain({
        content: prompt,
        provider: attempt.provider,
        systemPrompt: buildTitleSystemPrompt(),
        tools: [],
        callSite: "conversationTitle",
        signal,
        timeoutMs: 15_000,
      });
      title = normalizeTitle(result.text);
      if (title) break;
    } catch (err) {
      lastError = err;
      log.warn(
        { err, conversationId, profile: attempt.profile },
        "Conversation title regeneration provider attempt failed",
      );
    }
  }
  if (title) {
    // Re-check isAutoTitle before persisting (race guard against manual rename)
    const current = getConversation(conversationId);
    if (!current || !current.isAutoTitle) {
      return { title: current?.title ?? UNTITLED_FALLBACK, updated: false };
    }

    updateConversationTitle(conversationId, title, AUTO_TITLE_LLM);
    publishConversationTitleChanged(conversationId, title);
    log.info(
      { conversationId, title },
      "Re-generated conversation title (second pass)",
    );
    return { title, updated: true };
  }

  if (lastError) {
    log.warn(
      { err: lastError, conversationId },
      "All conversation title regeneration provider attempts failed",
    );
  }

  const fallbackMessage = recentMessages
    .filter((message) => message.role === "user")
    .map((message) => message.text)
    .filter(Boolean)
    .at(-1);
  if (fallbackMessage) {
    return persistFallbackTitle(
      conversationId,
      effectiveContext,
      fallbackMessage,
    );
  }
  return { title: conversation.title ?? UNTITLED_FALLBACK, updated: false };
}

/**
 * Repair a replaceable title from persisted conversation content.
 * Invoked only from explicit conversation activity; it never runs at startup.
 */
export async function repairConversationTitle(
  params: RegenerateTitleParams,
): Promise<{ title: string; updated: boolean }> {
  const conversation = getConversation(params.conversationId);
  if (!conversation || !canReplaceTitle(conversation)) {
    return {
      title: conversation?.title ?? UNTITLED_FALLBACK,
      updated: false,
    };
  }

  const messages = getMessages(params.conversationId);
  const userMessage = messages
    .filter((message) => message.role === "user")
    .map((message) => extractTextForTitle(message.content))
    .find((text) => text.trim().length > 0);
  const assistantResponse = messages
    .filter((message) => message.role === "assistant")
    .map((message) => extractTextForTitle(message.content))
    .find((text) => text.trim().length > 0);

  if (!userMessage) {
    if (conversation.title === GENERATING_TITLE) {
      return persistFallbackTitle(params.conversationId);
    }
    return {
      title: conversation.title ?? UNTITLED_FALLBACK,
      updated: false,
    };
  }

  return generateAndPersistConversationTitle({
    ...params,
    userMessage,
    assistantResponse,
  });
}

export function queueRepairConversationTitle(
  params: RegenerateTitleParams,
): void {
  assertPooledRuntimeAsyncOperationSupported("conversation title jobs");
  void titleMutex
    .withLock(async () => {
      await repairConversationTitle(params);
    })
    .catch((err) => {
      log.warn(
        { err, conversationId: params.conversationId },
        "Failed to repair conversation title (non-fatal)",
      );
    });
}

/**
 * Awaitable, serialized second-pass title generation for request-bound
 * runtimes. See {@link generateConversationTitleRequestBound}.
 */
export function regenerateConversationTitleRequestBound(
  params: RegenerateTitleParams,
): Promise<{ title: string; updated: boolean }> {
  return titleMutex.withLock(() => regenerateConversationTitle(params));
}

/**
 * Fire-and-forget wrapper for title regeneration.
 *
 * Serialized via the same {@link titleMutex} as initial generation.
 */
export function queueRegenerateConversationTitle(
  params: RegenerateTitleParams,
): void {
  assertPooledRuntimeAsyncOperationSupported("conversation title jobs");
  void regenerateConversationTitleRequestBound(params).catch((err) => {
    log.warn(
      { err, conversationId: params.conversationId },
      "Failed to regenerate conversation title (non-fatal)",
    );
  });
}

// ── Internal helpers ─────────────────────────────────────────────────

/**
 * Dedicated system prompt for title generation. Replaces the default
 * assistant system prompt that btw-sidechain would otherwise inject,
 * which caused the model to respond to the conversation content instead
 * of titling it.
 */
function buildTitleSystemPrompt(): string {
  return [
    "You generate ultra-concise conversation titles. Output ONLY the title text — no explanation, no quotes, no markdown, no preamble.",
    "",
    "Rules:",
    "- 2–5 words maximum. Titles longer than 5 words are unacceptable — ruthlessly compress to a short noun phrase",
    "- 40 characters absolute maximum — if your title exceeds 40 characters it will be truncated and look broken",
    "- Summarize only the TOPIC, not the request or instructions",
    "- Noun phrases are ideal (e.g. 'Auth Middleware Rewrite', 'Docker Volume Mounts', 'Onboarding Flow')",
    "- Think: what would make a scannable sidebar label?",
    "- Do NOT echo back what the user asked you to do",
    "- Do NOT respond to the conversation content",
    "- Do NOT assess feasibility or comment on capabilities",
    "- If input is sparse or references external context, extract a topic from the words that ARE present (e.g. 'so about that t-shirt...' → 'T-Shirt Discussion'). Never describe the absence, emptiness, or insufficiency of context — titles like 'Missing Context', 'Unclear Request', 'No Topic' are forbidden",
  ].join("\n");
}

function buildTitlePrompt(
  context?: TitleContext,
  userMessage?: string,
  assistantResponse?: string,
): string {
  const parts: string[] = [];

  if (context) {
    const hints: string[] = [];
    if (context.sourceChannel) hints.push(`Channel: ${context.sourceChannel}`);
    if (context.displayName) hints.push(`User: ${context.displayName}`);
    if (context.systemHint) hints.push(`Context: ${context.systemHint}`);
    if (context.uxBrief) hints.push(`Brief: ${context.uxBrief}`);
    if (context.metadataHints?.length)
      hints.push(`Hints: ${context.metadataHints.join(", ")}`);
    if (hints.length > 0) {
      parts.push("Metadata:", ...hints, "");
    }
  }

  if (userMessage) {
    parts.push(`User: ${stripThinkingTags(userMessage)}`);
  }
  if (assistantResponse) {
    parts.push(`Assistant: ${stripThinkingTags(assistantResponse)}`);
  }

  return parts.join("\n");
}

const META_FAILURE_TITLES = new Set([
  "missing context",
  "no context",
  "insufficient context",
  "unclear context",
  "empty context",
  "no topic",
  "unclear topic",
  "unclear request",
  "unclear message",
  "empty conversation",
  "empty message",
  "no content",
]);

const MAX_TITLE_LENGTH = 40;
const MAX_TITLE_WORDS = 7;

function truncateTitle(title: string): string {
  if (title.length <= MAX_TITLE_LENGTH) return title;
  const words = title.split(/\s+/);
  if (words.length <= MAX_TITLE_WORDS) {
    // Long words but few of them — truncate to char limit at word boundary
    let result = "";
    for (const word of words) {
      const candidate = result ? result + " " + word : word;
      if (candidate.length > MAX_TITLE_LENGTH) break;
      result = candidate;
    }
    return result || title.slice(0, MAX_TITLE_LENGTH);
  }
  // Too many words — trim to 5 words
  return words.slice(0, 5).join(" ");
}

function normalizeTitle(raw: string): string {
  let title = raw.trim().replace(/^["']|["']$/g, "");
  title = stripMarkdown(title);
  title = stripThinkingTags(title);
  if (META_FAILURE_TITLES.has(title.toLowerCase())) {
    return "";
  }
  return truncateTitle(title);
}

/** Strip thinking tags so they don't bleed into generated titles. */
function stripThinkingTags(text: string): string {
  return text
    .replace(/<thinking>[\s\S]*?<\/thinking>/gi, "")
    .replace(/<thought>[\s\S]*?<\/thought>/gi, "")
    .replace(/<think>[\s\S]*?<\/think>/gi, "")
    .replace(/<thought>/gi, "")
    .replace(/<\/thought>/gi, "")
    .replace(/<thinking>/gi, "")
    .replace(/<\/thinking>/gi, "")
    .replace(/<think>/gi, "")
    .replace(/<\/think>/gi, "")
    .replace(/<:[^>]*>/gi, "");
}

/** Strip common markdown formatting so titles render as plain text. */
function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "$1") // **bold**
    .replace(/__(.+?)__/g, "$1") // __bold__
    .replace(/\*(.+?)\*/g, "$1") // *italic*
    .replace(/(?<!\w)_(.+?)_(?!\w)/g, "$1") // _italic_ (word-boundary-aware to preserve snake_case)
    .replace(/~~(.+?)~~/g, "$1") // ~~strikethrough~~
    .replace(/`(.+?)`/g, "$1") // `code`
    .replace(/\[(.+?)\]\(.+?\)/g, "$1") // [link](url)
    .replace(/^#{1,6}\s+/gm, ""); // # headings
}

function deriveFallbackTitle(context?: TitleContext): string | null {
  if (!context) return null;
  if (context.systemHint) return context.systemHint;
  if (context.uxBrief) return context.uxBrief;
  return null;
}

function deriveMessageTitle(userMessage?: string): string | null {
  if (!userMessage) return null;

  const cleaned = stripMarkdown(stripThinkingTags(userMessage))
    .replace(/\s+/g, " ")
    .trim();
  if (!cleaned) return null;

  // Keep the first sentence when the prompt contains a long explanation. The
  // title remains useful even when the provider is unavailable.
  const firstSentence = cleaned.split(/(?<=[.!?])\s+/u)[0] ?? cleaned;
  const title = firstSentence.replace(/[.!?]+$/u, "").trim();
  if (!title) return null;
  return truncateTitle(title);
}

function persistFallbackTitle(
  conversationId: string,
  context?: TitleContext,
  userMessage?: string,
): { title: string; updated: boolean } {
  const current = getConversation(conversationId);
  if (current && !canReplaceTitle(current)) {
    return { title: current.title!, updated: false };
  }

  const fallback =
    deriveFallbackTitle(context) ??
    deriveMessageTitle(userMessage) ??
    UNTITLED_FALLBACK;
  updateConversationTitle(conversationId, fallback, AUTO_TITLE_DETERMINISTIC);
  publishConversationTitleChanged(conversationId, fallback);
  return { title: fallback, updated: true };
}

/**
 * Extract only human-authored text from stored message content for title
 * generation. Unlike extractTextFromStoredMessageContent (which includes
 * tool metadata like "Tool use (...): {...}"), this only extracts:
 * - `text` blocks (the actual conversation content)
 * - `tool_result` string content (topical signal from tool responses)
 *   — web_search_tool_result is skipped (structured search data, not topical)
 *
 * Returns empty string for content-block arrays with no extractable text,
 * preventing raw JSON from polluting the title prompt.
 */
function extractTextForTitle(raw: string): string {
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === "string") return parsed;
    if (!Array.isArray(parsed)) return raw;
    const texts: string[] = [];
    for (const block of parsed) {
      if (!block || typeof block !== "object") continue;
      if (block.type === "text" && typeof block.text === "string") {
        texts.push(block.text);
        // guard:allow-tool-result-only — web_search_tool_result has structured
        // search result arrays, not useful for title generation; only plain
        // tool_result string content carries topical signal.
      } else if (block.type === "tool_result") {
        if (typeof block.content === "string") {
          texts.push(block.content);
        } else if (Array.isArray(block.content)) {
          for (const nested of block.content) {
            if (
              nested &&
              typeof nested === "object" &&
              nested.type === "text" &&
              typeof nested.text === "string"
            ) {
              texts.push(nested.text);
            }
          }
        }
      }
    }
    return texts.join("\n");
  } catch {
    return raw;
  }
}

function buildRegenerationPrompt(
  recentMessages: ReadonlyArray<TitleTranscriptMessage>,
): string {
  const parts: string[] = ["Recent messages:"];

  for (const msg of recentMessages) {
    if (!msg.text) continue;
    const role = msg.role === "user" ? "User" : "Assistant";
    parts.push(`${role}: ${stripThinkingTags(msg.text)}`);
  }

  return parts.join("\n");
}
