import type {
  AssistantCharacterPackId,
  AssistantFaceBuilderConfig,
} from "@/types/assistant-character-profile";

export type FaceBuilderCategoryId =
  | "skinTone"
  | "hair"
  | "eyes"
  | "brows"
  | "eyewear"
  | "nose"
  | "mouth"
  | "accessories"
  | "lineStyle"
  | "background";

export interface FaceBuilderOption {
  id: string;
  label: string;
  preview: string;
}

export interface FaceBuilderCategory {
  id: FaceBuilderCategoryId;
  label: string;
  icon: string;
  options: FaceBuilderOption[];
}

export const DEFAULT_FACE_BUILDER: AssistantFaceBuilderConfig = {
  skinTone: "paper",
  hair: "messy",
  eyes: "curious",
  brows: "soft",
  eyewear: "none",
  nose: "simple",
  mouth: "smile",
  accessories: "none",
  lineStyle: "clean",
  background: "white",
};

export const FACE_BUILDER_CATEGORIES: FaceBuilderCategory[] = [
  {
    id: "skinTone",
    label: "Skin tone",
    icon: "●",
    options: [
      { id: "paper", label: "Paper", preview: "○" },
      { id: "pale", label: "Pale", preview: "◐" },
      { id: "yellow", label: "Yellow", preview: "●" },
      { id: "tan", label: "Tan", preview: "●" },
      { id: "brown", label: "Brown", preview: "●" },
      { id: "steel", label: "Steel", preview: "◉" },
      { id: "red", label: "Red", preview: "●" },
      { id: "green", label: "Green", preview: "●" },
    ],
  },
  {
    id: "hair",
    label: "Hair",
    icon: "▥",
    options: [
      { id: "none", label: "None", preview: "—" },
      { id: "messy", label: "Messy", preview: "≋" },
      { id: "spiky", label: "Spiky", preview: "✸" },
      { id: "short", label: "Short", preview: "▰" },
      { id: "swoop", label: "Swoop", preview: "〰" },
      { id: "tall", label: "Tall", preview: "▥" },
      { id: "buns", label: "Buns", preview: "∞" },
      { id: "tentacles", label: "Tentacles", preview: "≋" },
      { id: "tuft", label: "Tuft", preview: "⌁" },
      { id: "antenna", label: "Antenna", preview: "⌁" },
    ],
  },
  {
    id: "eyes",
    label: "Eyes",
    icon: "◔",
    options: [
      { id: "curious", label: "Curious", preview: "• •" },
      { id: "wide", label: "Wide", preview: "● ●" },
      { id: "sleepy", label: "Sleepy", preview: "⌒ ⌒" },
      { id: "one", label: "One eye", preview: "◉" },
      { id: "visor", label: "Visor", preview: "▬" },
      { id: "tiny", label: "Tiny", preview: "· ·" },
      { id: "spiral", label: "Spiral", preview: "◉ ◉" },
      { id: "heart", label: "Heart", preview: "♥ ♥" },
    ],
  },
  {
    id: "brows",
    label: "Brows",
    icon: "⌒",
    options: [
      { id: "none", label: "None", preview: "—" },
      { id: "soft", label: "Soft", preview: "⌒ ⌒" },
      { id: "sharp", label: "Sharp", preview: "⌃ ⌃" },
      { id: "worried", label: "Worried", preview: "╱ ╲" },
      { id: "flat", label: "Flat", preview: "─ ─" },
      { id: "heavy", label: "Heavy", preview: "▂ ▂" },
    ],
  },
  {
    id: "eyewear",
    label: "Eyewear",
    icon: "∞",
    options: [
      { id: "none", label: "None", preview: "—" },
      { id: "round", label: "Round", preview: "○○" },
      { id: "square", label: "Square", preview: "□□" },
      { id: "visor", label: "Visor", preview: "▭" },
      { id: "monocle", label: "Monocle", preview: "○" },
    ],
  },
  {
    id: "nose",
    label: "Nose",
    icon: "└",
    options: [
      { id: "simple", label: "Simple", preview: "╎" },
      { id: "long", label: "Long", preview: "└" },
      { id: "button", label: "Button", preview: "◦" },
      { id: "hook", label: "Hook", preview: "⌞" },
      { id: "angular", label: "Angular", preview: "∟" },
      { id: "none", label: "None", preview: "—" },
    ],
  },
  {
    id: "mouth",
    label: "Mouth",
    icon: "◡",
    options: [
      { id: "smile", label: "Smile", preview: "⌣" },
      { id: "smirk", label: "Smirk", preview: "⌒" },
      { id: "flat", label: "Flat", preview: "─" },
      { id: "open", label: "Open", preview: "○" },
      { id: "grimace", label: "Grimace", preview: "▭" },
      { id: "beard", label: "Beard", preview: "⌣" },
      { id: "mustache", label: "Mustache", preview: "⌁" },
    ],
  },
  {
    id: "accessories",
    label: "Accessories",
    icon: "✦",
    options: [
      { id: "none", label: "None", preview: "—" },
      { id: "lab", label: "Lab coat", preview: "▱" },
      { id: "crown", label: "Crown", preview: "♛" },
      { id: "antenna", label: "Antenna", preview: "⌁" },
      { id: "earring", label: "Earring", preview: "•" },
      { id: "tie", label: "Tie", preview: "♦" },
    ],
  },
  {
    id: "lineStyle",
    label: "Line",
    icon: "✎",
    options: [
      { id: "clean", label: "Clean", preview: "━" },
      { id: "ink", label: "Ink", preview: "〰" },
      { id: "halftone", label: "Halftone", preview: "░" },
    ],
  },
  {
    id: "background",
    label: "Backdrop",
    icon: "◌",
    options: [
      { id: "white", label: "White", preview: "○" },
      { id: "black", label: "Black", preview: "●" },
      { id: "navy", label: "Navy", preview: "●" },
      { id: "portal", label: "Portal", preview: "◎" },
      { id: "warm", label: "Warm", preview: "●" },
    ],
  },
];

type CharacterPresetKey = `${AssistantCharacterPackId}:${string}`;

const PRESETS: Record<string, AssistantFaceBuilderConfig> = {
  "rick_and_morty:rick": {
    skinTone: "pale",
    hair: "spiky",
    eyes: "sleepy",
    brows: "heavy",
    eyewear: "none",
    nose: "long",
    mouth: "flat",
    accessories: "lab",
    lineStyle: "ink",
    background: "portal",
  },
  "rick_and_morty:morty": {
    skinTone: "tan",
    hair: "short",
    eyes: "wide",
    brows: "worried",
    eyewear: "none",
    nose: "button",
    mouth: "flat",
    accessories: "none",
    lineStyle: "clean",
    background: "warm",
  },
  "rick_and_morty:summer": {
    skinTone: "tan",
    hair: "swoop",
    eyes: "sleepy",
    brows: "sharp",
    eyewear: "none",
    nose: "simple",
    mouth: "smirk",
    accessories: "earring",
    lineStyle: "clean",
    background: "warm",
  },
  "rick_and_morty:beth": {
    skinTone: "tan",
    hair: "swoop",
    eyes: "sleepy",
    brows: "flat",
    eyewear: "none",
    nose: "long",
    mouth: "flat",
    accessories: "lab",
    lineStyle: "clean",
    background: "white",
  },
  "rick_and_morty:jerry": {
    skinTone: "tan",
    hair: "short",
    eyes: "curious",
    brows: "worried",
    eyewear: "none",
    nose: "button",
    mouth: "smile",
    accessories: "tie",
    lineStyle: "clean",
    background: "warm",
  },
  "rick_and_morty:mr_meeseeks": {
    skinTone: "pale",
    hair: "none",
    eyes: "wide",
    brows: "sharp",
    eyewear: "none",
    nose: "button",
    mouth: "open",
    accessories: "none",
    lineStyle: "clean",
    background: "navy",
  },
  "rick_and_morty:evil_morty": {
    skinTone: "pale",
    hair: "short",
    eyes: "visor",
    brows: "flat",
    eyewear: "none",
    nose: "simple",
    mouth: "flat",
    accessories: "none",
    lineStyle: "clean",
    background: "black",
  },
  "rick_and_morty:space_beth": {
    skinTone: "tan",
    hair: "swoop",
    eyes: "sleepy",
    brows: "sharp",
    eyewear: "none",
    nose: "long",
    mouth: "smirk",
    accessories: "lab",
    lineStyle: "ink",
    background: "navy",
  },
  "simpsons:homer": {
    skinTone: "yellow",
    hair: "tuft",
    eyes: "wide",
    brows: "none",
    eyewear: "none",
    nose: "button",
    mouth: "open",
    accessories: "none",
    lineStyle: "clean",
    background: "warm",
  },
  "simpsons:marge": {
    skinTone: "yellow",
    hair: "tall",
    eyes: "curious",
    brows: "soft",
    eyewear: "none",
    nose: "simple",
    mouth: "smile",
    accessories: "none",
    lineStyle: "clean",
    background: "white",
  },
  "simpsons:bart": {
    skinTone: "yellow",
    hair: "spiky",
    eyes: "curious",
    brows: "sharp",
    eyewear: "none",
    nose: "button",
    mouth: "smirk",
    accessories: "none",
    lineStyle: "clean",
    background: "warm",
  },
  "simpsons:lisa": {
    skinTone: "yellow",
    hair: "spiky",
    eyes: "wide",
    brows: "soft",
    eyewear: "none",
    nose: "button",
    mouth: "flat",
    accessories: "none",
    lineStyle: "clean",
    background: "white",
  },
  "simpsons:maggie": {
    skinTone: "yellow",
    hair: "spiky",
    eyes: "wide",
    brows: "soft",
    eyewear: "none",
    nose: "button",
    mouth: "flat",
    accessories: "none",
    lineStyle: "clean",
    background: "white",
  },
  "simpsons:mr_burns": {
    skinTone: "yellow",
    hair: "tuft",
    eyes: "sleepy",
    brows: "heavy",
    eyewear: "none",
    nose: "hook",
    mouth: "smirk",
    accessories: "crown",
    lineStyle: "ink",
    background: "black",
  },
  "simpsons:moe": {
    skinTone: "yellow",
    hair: "short",
    eyes: "sleepy",
    brows: "heavy",
    eyewear: "none",
    nose: "angular",
    mouth: "flat",
    accessories: "none",
    lineStyle: "ink",
    background: "black",
  },
  "simpsons:ralph": {
    skinTone: "yellow",
    hair: "short",
    eyes: "wide",
    brows: "soft",
    eyewear: "none",
    nose: "button",
    mouth: "smile",
    accessories: "none",
    lineStyle: "clean",
    background: "white",
  },
  "futurama:fry": {
    skinTone: "tan",
    hair: "swoop",
    eyes: "wide",
    brows: "worried",
    eyewear: "none",
    nose: "simple",
    mouth: "smile",
    accessories: "none",
    lineStyle: "clean",
    background: "warm",
  },
  "futurama:leela": {
    skinTone: "tan",
    hair: "swoop",
    eyes: "one",
    brows: "sharp",
    eyewear: "none",
    nose: "simple",
    mouth: "flat",
    accessories: "none",
    lineStyle: "clean",
    background: "navy",
  },
  "futurama:bender": {
    skinTone: "steel",
    hair: "antenna",
    eyes: "visor",
    brows: "none",
    eyewear: "none",
    nose: "none",
    mouth: "grimace",
    accessories: "antenna",
    lineStyle: "clean",
    background: "black",
  },
  "futurama:professor": {
    skinTone: "pale",
    hair: "tuft",
    eyes: "wide",
    brows: "heavy",
    eyewear: "round",
    nose: "long",
    mouth: "open",
    accessories: "lab",
    lineStyle: "ink",
    background: "white",
  },
  "futurama:zoidberg": {
    skinTone: "red",
    hair: "tentacles",
    eyes: "wide",
    brows: "soft",
    eyewear: "none",
    nose: "none",
    mouth: "open",
    accessories: "none",
    lineStyle: "ink",
    background: "warm",
  },
  "futurama:nibbler": {
    skinTone: "brown",
    hair: "none",
    eyes: "wide",
    brows: "heavy",
    eyewear: "none",
    nose: "button",
    mouth: "smirk",
    accessories: "crown",
    lineStyle: "ink",
    background: "black",
  },
  "futurama:amy": {
    skinTone: "tan",
    hair: "swoop",
    eyes: "curious",
    brows: "soft",
    eyewear: "none",
    nose: "button",
    mouth: "smile",
    accessories: "earring",
    lineStyle: "clean",
    background: "warm",
  },
  "futurama:hermes": {
    skinTone: "brown",
    hair: "short",
    eyes: "curious",
    brows: "flat",
    eyewear: "square",
    nose: "simple",
    mouth: "flat",
    accessories: "tie",
    lineStyle: "clean",
    background: "white",
  },
  "futurama:mom": {
    skinTone: "pale",
    hair: "tall",
    eyes: "sleepy",
    brows: "sharp",
    eyewear: "none",
    nose: "hook",
    mouth: "smirk",
    accessories: "crown",
    lineStyle: "ink",
    background: "black",
  },
  "futurama:zapp": {
    skinTone: "tan",
    hair: "swoop",
    eyes: "sleepy",
    brows: "heavy",
    eyewear: "none",
    nose: "angular",
    mouth: "smirk",
    accessories: "none",
    lineStyle: "clean",
    background: "warm",
  },
  "futurama:kif": {
    skinTone: "green",
    hair: "none",
    eyes: "sleepy",
    brows: "worried",
    eyewear: "none",
    nose: "button",
    mouth: "flat",
    accessories: "none",
    lineStyle: "clean",
    background: "white",
  },
};

export function faceBuilderForCharacter(
  packId: AssistantCharacterPackId,
  characterId: string,
): AssistantFaceBuilderConfig {
  const key: CharacterPresetKey = `${packId}:${characterId}`;
  const preset = PRESETS[key];
  return { ...DEFAULT_FACE_BUILDER, ...(preset ?? {}) };
}

export function buildCharacterPortraitPrompt(
  characterName: string,
  packLabel: string,
): string {
  return [
    `Square transparent PNG avatar portrait of ${characterName} from ${packLabel}.`,
    "Make the character immediately recognizable and faithful to the adult animated TV source.",
    "Head-and-shoulders crop, centered, clean edges, expressive face, crisp linework, high resolution.",
    "No background, no text, no watermark, no frame, no extra characters.",
    "Friendly polished product-avatar finish suitable for a SaaS assistant identity picker.",
  ].join(" ");
}
